### ISSUE TITLE
New contributers can contribute here by just entring inn there names and joining 

### ISSUE THREAD

**Issue by Ishaan28malik** [Ishaan28malik/HACKTOBERFEST2019#1]
Just fork this repo ,star it, clone it and add or just make a new file with the file as your name and

**Comment by orestotel** [comment]
#34 Added my link

**Comment by Ishaan28malik** [comment]
Still Open for #104

**Comment by sharion64** [comment]
#138 added my name and link

**Comment by bosecodes** [comment]
#138 added my name and profile link
