### ISSUE TITLE
Ishaan28malik/Hacktoberfest2019 excluded from Hacktoberfest

### ISSUE THREAD

**Issue by mskadu** [Ishaan28malik/Hacktoberfest2019#550]
Hi there,

Thanks for making your repo available to Hacktoberfest 2019. I've just noticed that your repo has been excluded from being counted towards contributions.

Shame really, but I thought I should say thanks all the same. :)

**Comment by Ishaan28malik** [comment]
Sure @mskadu

**Comment by Ishaan28malik** [comment]
I know that's true man, can we do anything for this man? @mskadu

**Comment by mskadu** [comment]
I am good. My colleagues and I started [this repo](https://github.com/mskadu/GitCoopDemo) which will eventually morph into something we will work on together in the future - hopefully.

Thanks anyway 👍

**Comment by Ishaan28malik** [comment]
Oh cool .Sounds great @mskadu
